### ISSUE TITLE
from JSON to XML

### ISSUE THREAD

**Issue by mrgren** [smart-fun/XmlToJson#1]
is there any way to do the inverse process
mean => from Json to XML ?
thanks

**Comment by smart-fun** [comment]
Hello and thank you for your message.
It is not possible at the moment, but this is something I could do if people want it.
But I was wondering why would you need to go from json to xml, json is so easier to use^^
Do you have a concrete example in mind?

**Comment by smart-fun** [comment]
I have just added a converter from JSON to XML. Use version 1.2.0 and read the documentation for How to use :)
