### ISSUE TITLE
org.xmlpull.v1.XmlPullParserException: attr value delimiter missing! (position:START_TAG <root author='1.0'>@1:52 in java.io.StringReader@26f223d) 

### ISSUE THREAD

**Issue by tank21** [smart-fun/XmlToJson#12]
org.xmlpull.v1.XmlPullParserException: attr value delimiter missing! (position:START_TAG <root author='1.0'>@1:52 in java.io.StringReader@26f223d)

**Comment by smart-fun** [comment]
hello
could you please attach or copy/paste your xml file so that I can try to reproduce the issue?

thanks,

Arnaud.

**Comment by tank21** [comment]
<?xml version="1.0" encoding="utf-8"?><CMD_RES code="1" index="1" res="1"><AP index = "0"><SSID>AP1</SSID><ENCRYP_MODE>WPA2PSK/AES</ENCRYP_MODE><SIGNAL>63</SIGNAL></AP><AP index = "1"><SSID>WX-Distinct</SSID><ENCRYP_MODE>0a:18:d6:cf:03:17</ENCRYP_MODE><SIGNAL>WPA110</SIGNAL></AP><AP index = "2"><SSID>luftmed_yanfa</SSID><ENCRYP_MODE>WPA1PSKWPA2PSK/TKIPAES</ENCRYP_MODE><SIGNAL>100</SIGNAL></AP><AP index = "3"><SSID>ADS01</SSID><ENCRYP_MODE>WPA2PSK/AES</ENCRYP_MODE><SIGNAL>15</SIGNAL></AP><AP index = "4"><SSID>SENATOR</SSID><ENCRYP_MODE>WPA2PSK/AES</ENCRYP_MODE><SIGNAL>39</SIGNAL></AP></CMD_RES>

**Comment by smart-fun** [comment]
I close this issue as I have no information.

**Comment by tank21** [comment]
I've already solved it. It's in my XML format. Thank you
