### ISSUE TITLE
Different values from attribute

### ISSUE THREAD

**Issue by areeev** [smart-fun/XmlToJson#13]
Hello,
I try to convert this [link](https://www.bola.net/feed) in the xml file there is the enclosure tag and want to get the value from the attribute url. But after the conversion attribute value changed from xml tag

`<enclosure url="https://cdns.klimg.com/bola.net/library/upload/21/2017/11/hl-werner_c6335a2.jpg" length="97399" type="image/jpeg"/>` 

to json

`"enclosure":             {
                                                                                  "length": "20854",
                                                                                  "type": "image\/jpeg",
                                                                                  "url": "https:\/\/cdns.klimg.com\/bola.net\/library\/\/320x160\/p\/headline\/0000374549.jpg"
                                                                               }`

then i try to convert using rss2json.com and the converted xml is the same as the original document.

any suggestion?

Thank you.

the code
` public void XMLtoJson(String xmlString){

        XmlToJson xmlToJson = new XmlToJson.Builder(xmlString)
                .build();

        Log.d(LOG_TAG, xmlToJson.toFormattedString());

    } `

**Comment by smart-fun** [comment]
Hello Slopy and thank you for your feedback !

when the whole XmlToJson is converted to a String (or a formatted String), all special characters have to be escaped, or it won't be possible to create a JSONObject from that String after.

BUT

If you convert directly the XmlToJson to a JSONObject and parse it, then you can retrieve the url in a standard String like : "`https://cdns.klimg.com/bola.net/library/upload/21/2017/12/west-ham-vs-chelsea_d405b56.jpg
`"

So here is the code you are looking for:
```
XmlToJson xmlToJson = new XmlToJson.Builder(xmlString).build();
JSONObject json = xmlToJson.toJson();
JSONObject rss = json.getJSONObject("rss");
JSONObject channel = rss.getJSONObject("channel");
JSONArray items = channel.getJSONArray("item");
for(int i=0; i<items.length(); ++i) {
    JSONObject item = items.getJSONObject(i);
    JSONObject enclosure = item.getJSONObject("enclosure");
    String url = enclosure.getString("url");
    Log.i(TAG, "url: " + url);
}
```

Arnaud.
