### ISSUE TITLE
What is ProGuard rules？

### ISSUE THREAD

**Issue by NicodeLee** [smart-fun/XmlToJson#17]

**Comment by smart-fun** [comment]
Hello,

I'm not sure to understand your question.

If you want to know what ProGuard is, I suggest you read this:
https://www.guardsquare.com/en/products/proguard

If you want to know what rules are applied on the XmlToJson library, I use the default proguard settings for Android projects (all is generated by Android Studio).

**Comment by NicodeLee** [comment]
Thanks.
