### ISSUE TITLE
Force list paths: use patterns instead of full paths

### ISSUE THREAD

**Issue by relaxedSoul** [smart-fun/XmlToJson#21]
Hello!

I have the XML file where there are nodes containing the nodes of the same type. and sometimes there is 1 element, sometimes there are several of them.
Example: 
```
<catalog>
  <categories>
    <category/>
    <category>
      <categories>
        <category/>
      </categories>
    </category>
  </categories>
</catalog>
```

In Obj presentation it will be simple: 

```
class Category {
    @Nullable
    Categories categories;
    // ... other meaningful fields
}

class Categories {
    // at least 1 item 
    List<Category> list;
}
```

So, I need to force all these lists to be a lists instead of 1 item property.
```
.forceList("/catalog/categories/category")
.forceList("/catalog/categories/category/categories/category")
.forceList("/catalog/categories/category/categories/category/categories/category")

```

But my source XML can have infinite complexity. I need to have something like that: 
`.forceList("./categories/category")`
or 
`.forceList("*/categories/category")`

Can you improve the check of the tags so it will not search for an exact path, but will search for the pattern, or any other kind of regex-like structure?

Probably, it should be the method called `forceListPattern(String pattern)`

**Comment by smart-fun** [comment]
Hello Dmitri

I have started to look into this request and have probably a solution for this, but I need some time as I don't master regex. For example * does not compile, but I can use "category$". Probably I'll ask you to check / validate the changes I'm about to make before I publish for everyone.

Arnaud.

**Comment by relaxedSoul** [comment]
@smart-fun Hello!

I made a mistake with `*`. Correct would be `.forceList(".*/categories/category")` 

Let me make a PR maybe you will like the solution I suggest. There are 1 additional method, tests for it.

**Comment by javadev** [comment]
```xml
<catalog>
  <categories>
    <category/>
    <category>
      <categories>
        <category/>
      </categories>
    </category>
  </categories>
</catalog>
```

May be converted to json:
```json
{
  "catalog": {
    "categories": {
      "category": [
        {
          "-self-closing": "true"
        },
        {
          "categories": {
            "category": {
              "-self-closing": "true"
            }
          }
        }
      ]
    }
  },
  "#omit-xml-declaration": "yes"
}
```

**Comment by smart-fun** [comment]
Hello @relaxedSoul and @javadev 

sorry for the delay. I did add a method long ago for regex but didn't push.

I just tried a little as I'm not comfortable with regex. Could you please give a try to the 1.5.0 pre-release?

the new method in the builder is: **forceListPattern(String pattern)**

thanks!
