### ISSUE TITLE
xml to json error name;

### ISSUE THREAD

**Issue by lcw1987565** [smart-fun/XmlToJson#3]
I have found a problem:
xml =
`<?xml version="1.0" encoding="gb2312"?><root>
	<data>
		<responsedata>
			<entity rowNum="0">
				<PARAM>用户名</PARAM>
				<PARAM_TYPE>1</PARAM_TYPE>
				<PARAM_VALUE>周玉英</PARAM_VALUE>
				<PARAM_LENGTH/>
				<TYPE>1</TYPE>
				<PARAM_CODE>userName</PARAM_CODE>
				<HTML_TYPE>text</HTML_TYPE>
			</entity>
			<entity rowNum="1">
				<PARAM>联系电话</PARAM>
				<PARAM_TYPE>1</PARAM_TYPE>
				<PARAM_VALUE/>
				<PARAM_LENGTH/>
				<TYPE>1</TYPE>
				<PARAM_CODE>userPhone</PARAM_CODE>
				<HTML_TYPE>text</HTML_TYPE>
			</entity>
			<entity rowNum="2">
				<PARAM>设备号</PARAM>
				<PARAM_TYPE>1</PARAM_TYPE>
				<PARAM_VALUE>AD0001595170</PARAM_VALUE>
				<PARAM_LENGTH/>
				<TYPE>1</TYPE>
				<PARAM_CODE>dealCode</PARAM_CODE>
				<HTML_TYPE>text</HTML_TYPE>
			</entity>
			<entity rowNum="3">
				<PARAM>工作时间</PARAM>
				<PARAM_TYPE>1</PARAM_TYPE>
				<PARAM_VALUE/>
				<PARAM_LENGTH/>
				<TYPE>1</TYPE>
				<PARAM_CODE>workTime</PARAM_CODE>
				<HTML_TYPE>datetime</HTML_TYPE>
			</entity>
			<entity rowNum="4">
				<PARAM>工作大类</PARAM>
				<PARAM_TYPE>1</PARAM_TYPE>
				<PARAM_VALUE/>
				<PARAM_LENGTH/>
				<TYPE>1</TYPE>
				<PARAM_CODE>workType</PARAM_CODE>
				<HTML_TYPE>select</HTML_TYPE>
				<PARAM_DICT rowNum="1">
					<entity rowNum="0">
						<ID>repair</ID>
						<NAME>故障修理</NAME>
					</entity>
				</PARAM_DICT>
			</entity>
			<entity rowNum="5">
				<PARAM>结案原因</PARAM>
				<PARAM_TYPE>1</PARAM_TYPE>
				<PARAM_VALUE/>
				<PARAM_LENGTH/>
				<TYPE>1</TYPE>
				<PARAM_CODE>faultCause</PARAM_CODE>
				<HTML_TYPE>tree</HTML_TYPE>
				<PARAM_DICT rowNum="3">
					<entity rowNum="0">
						<ID>01-01</ID>
						<NAME>电缆修复</NAME>
						<SPECIALTYID>0057381</SPECIALTYID>
						<GROUPID>01</GROUPID>
					</entity>
					<entity rowNum="1">
						<ID>01-03</ID>
						<NAME>电缆开头子修复</NAME>
						<SPECIALTYID>0057381</SPECIALTYID>
						<GROUPID>01</GROUPID>
					</entity>
					<entity rowNum="2">
						<ID>01-07</ID>
						<NAME>电缆公务</NAME>
						<SPECIALTYID>0057381</SPECIALTYID>
						<GROUPID>01</GROUPID>
					</entity>
				</PARAM_DICT>
			</entity>
			<result>1</result>
			<result_info>成功</result_info>
		</responsedata>
	</data>
</root>`

`XmlToJson xmlToJson = new XmlToJson.Builder(xmlString)
                    .forceList("/root/data/responsedata/entity/PARAM_DICT/entity")
                    .forceList("/root/data/responsedata/entity")
                    .build();
String jsonStr = xmlToJson.toJson().toString();
`

will i get the result is:

the "rowNum" should be “entity”；
`{
					"PARAM_DICT": {
						"rowNum": [{  
							"ID": "repair",
							"rowNum": 0,
							"NAME": "故障修理"
						}]
					},
					"PARAM_TYPE": 1,
					"HTML_TYPE": "select",
					"PARAM_CODE": "workType",
					"PARAM": "工作大类",
					"rowNum": 4,
					"TYPE": 1
				}`

full json:
`{
	"root": {
		"data": {
			"responsedata": {
				"result": 1,
				"result_info": "成功",
				"entity": [{
					"PARAM_TYPE": 1,
					"HTML_TYPE": "text",
					"PARAM_CODE": "userName",
					"PARAM": "用户名",
					"PARAM_VALUE": "周玉英",
					"rowNum": 0,
					"TYPE": 1
				},
				{
					"PARAM_TYPE": 1,
					"HTML_TYPE": "text",
					"PARAM_CODE": "userPhone",
					"PARAM": "联系电话",
					"rowNum": 1,
					"TYPE": 1
				},
				{
					"PARAM_TYPE": 1,
					"HTML_TYPE": "text",
					"PARAM_CODE": "dealCode",
					"PARAM": "设备号",
					"PARAM_VALUE": "AD0001595170",
					"rowNum": 2,
					"TYPE": 1
				},
				{
					"PARAM_TYPE": 1,
					"HTML_TYPE": "datetime",
					"PARAM_CODE": "workTime",
					"PARAM": "工作时间",
					"rowNum": 3,
					"TYPE": 1
				},
				{
					"PARAM_DICT": {
						"rowNum": [{
							"ID": "repair",
							"rowNum": 0,
							"NAME": "故障修理"
						}]
					},
					"PARAM_TYPE": 1,
					"HTML_TYPE": "select",
					"PARAM_CODE": "workType",
					"PARAM": "工作大类",
					"rowNum": 4,
					"TYPE": 1
				},
				{
					"PARAM_DICT": {
						"rowNum": 3,
						"entity": [{
							"ID": "01-01",
							"SPECIALTYID": 57381,
							"NAME": "电缆修复",
							"rowNum": 0,
							"GROUPID": 1
						},
						{
							"ID": "01-03",
							"SPECIALTYID": 57381,
							"NAME": "电缆开头子修复",
							"rowNum": 1,
							"GROUPID": 1
						},
						{
							"ID": "01-07",
							"SPECIALTYID": 57381,
							"NAME": "电缆公务",
							"rowNum": 2,
							"GROUPID": 1
						}]
					},
					"PARAM_TYPE": 1,
					"HTML_TYPE": "tree",
					"PARAM_CODE": "faultCause",
					"PARAM": "结案原因",
					"rowNum": 5,
					"TYPE": 1
				}]
			}
		}
	}
}`

**Comment by smart-fun** [comment]
Hello!

thanks for reporting this issue, I'm looking into it right now.

I'm sorry for this bug, I tell you when I have a fix for it.

Arnaud.

**Comment by smart-fun** [comment]
Hi,

sorry for the delay, I was quite busy these days. I have made a fix and published it (version 1.2.2). All my unit tests pass so it should be ok. Please tell me if this fixes your problem (I'm sure it will ^^) so that I will close this issue.

thanks again for reporting,

Arnaud.

**Comment by smart-fun** [comment]
Hello,

I close this ticket as it is supposed to be fixed with the latest release.

Arnaud.
