### ISSUE TITLE
Replace com.android.support:support-annotations with AndroidX library

### ISSUE THREAD

**Issue by malloth** [smart-fun/XmlToJson#31]
Please replace `com.android.support:support-annotations` with the implementation from AndroidX to remove the necessity of having to use a Jetifier in the project.

**Comment by smart-fun** [comment]
Hi! Done :)
Use version 1.5.3
Replaced support library with androidx for annotations & unit tests.
Now MinSDK is 14 instead of 9 due to new androidx libraries.

Please confirm all is OK on your side so that I can close this issue.

**Comment by malloth** [comment]
Hello,

It works! Thank you very much for such a quick reaction.

Best reagrds.
