### ISSUE TITLE
XmlToJson.Builder(xml_string).build() crashes

### ISSUE THREAD

**Issue by ravindu1024** [smart-fun/XmlToJson#8]
So far I could only reproduce this on a Galaxy S3 running KitKat (API 19). 

W/System.err(25879): org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:19 in java.io.InputStreamReader@4219a840) 
W/System.err(25879): 	at org.kxml2.io.KXmlParser.readEntity(KXmlParser.java:1210)
W/System.err(25879): 	at org.kxml2.io.KXmlParser.readValue(KXmlParser.java:1392)
W/System.err(25879): 	at org.kxml2.io.KXmlParser.next(KXmlParser.java:390)
W/System.err(25879): 	at org.kxml2.io.KXmlParser.next(KXmlParser.java:310)
W/System.err(25879): 	at fr.arnaudguyon.xmltojsonlib.XmlToJson.readTags(XmlToJson.java:212)
W/System.err(25879): 	at fr.arnaudguyon.xmltojsonlib.XmlToJson.convertToJSONObject(XmlToJson.java:174)
W/System.err(25879): 	at fr.arnaudguyon.xmltojsonlib.XmlToJson.<init>(XmlToJson.java:145)
W/System.err(25879): 	at fr.arnaudguyon.xmltojsonlib.XmlToJson.<init>(XmlToJson.java:42)
W/System.err(25879): 	at fr.arnaudguyon.xmltojsonlib.XmlToJson$Builder.build(XmlToJson.java:125)
W/System.err(25879): 	at au.com.easyweddings.supplier.ui.NewsAndEducationActivity$1.onVelocitySuccess(NewsAndEducationActivity.java:129)
W/System.err(25879): 	at com.rw.velocity.Request$2.run(Request.java:357)
W/System.err(25879): 	at android.os.Handler.handleCallback(Handler.java:733)
W/System.err(25879): 	at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err(25879): 	at android.os.Looper.loop(Looper.java:146)
W/System.err(25879): 	at android.app.ActivityThread.main(ActivityThread.java:5487)
W/System.err(25879): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(25879): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err(25879): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
W/System.err(25879): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
W/System.err(25879): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by smart-fun** [comment]
Hello!

thanks for your feedback and sorry for the crash :/

Could you send me the xml file that makes the app crash?
Did you try to reproduce only with this device?
Did you try with the emulator?

thanks!

Arnaud.

**Comment by ravindu1024** [comment]
Hi Arnaud,

Unfortunately (and wierdly) I could only see this on the S3. It works fine
on other phones and other emulators.

Also, it works on the S3 when I run it in debug mode and add a breakpoint
at the build line.

This is the XML I'm using - www.easyweddings.com.au/pro-education/feed

On 17 Jul. 2017 5:47 pm, "Arnaud Guyon" <notifications@github.com> wrote:

Hello!

thanks for your feedback and sorry for the crash :/

Could you send me the xml file that makes the app crash?
Did you try to reproduce only with this device?
Did you try with the emulator?

thanks!

Arnaud.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/smart-fun/XmlToJson/issues/8#issuecomment-315687361>,
or mute the thread

**Comment by smart-fun** [comment]
Hi,

Not reproduced so far. I have a S3 at work I'll check with it when I have time.

Did you try to copy/paste the xml into a file located in your assets folder, and use it instead of the URL?
Just to check wheter the problem comes from reading the feed, or the xml content.

thanks,

Arnaud.

**Comment by ravindu1024** [comment]
HI,

It happens even when I try to parse the string using DocumentBuilder so I assume its a very specific system issue rather than a bug that you could fix. I'm closing this issue. Thanks for your time.
