### ISSUE TITLE
escaping double quote ?

### ISSUE THREAD

**Issue by ipinz** [smart-fun/XmlToJson#9]
xml tag sample from rss feed:
`<description><![CDATA[<img src="http://cdn.link.net/154335.jpg" align="left" hspace="7" width="120" height="90"/>any desc here.]]></description>`

xmlToJson.toFormattedString() result: 
`"description": "<img src="http://cdn.link.net/154335.jpg" align="left" hspace="7" width="120" height="90"/>any desc here."`

**Comment by smart-fun** [comment]
Thank you for reporting this issue. I will have a look at it.

**Comment by smart-fun** [comment]
Hello,
I have made a fix.
Please use version 1.3.6.
thanks again!
Arnaud.
